### ISSUE TITLE
breaks with django 2.1

### ISSUE THREAD

**Issue by emg36** [timheap/django-enumchoicefield#10]
Need to add renderer=None to forms render function to fix. See https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-2-1

**Comment by jLebioda** [comment]
Looks like the merge request targetting this issue has been accepted; could you bump the version and update the pip entry, please?

**Comment by assembledadam** [comment]
+1

**Comment by neoflex** [comment]
+1

**Comment by timheap** [comment]
Version 1.1.0 with Django 2.1 support has just been released :+1:
